apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - selfsigned-cluster-issuer.yaml
  - root-ca-certificate.yaml
  - local-ca-cluster-issuer.yaml
  - mam-wildcard-certificate.yaml
