apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: zitadel-auth-issuer
  namespace: longhorn-system
spec:
  endpoints:
    - fqdn:
        hostname: auth.mam.jku.internal
        port: 443
