apiVersion: v1
kind: Secret
metadata:
    name: zitadel-masterkey
    namespace: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:Ulz55NwY64oJBAwbLF557z7dObrf5b9ysDCHxfehRjE=,iv:wDSBPSdq5vFKN3UbwDkxBhztxpdUaZ23BXkpCtGfLMs=,tag:q/8Cn7g4IQPeVUN8jJkbIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUnZtVy9jK05mQjBVWDhG
            WDEyMDJLOE1oR2VkbEl3TzZqVWppUUR2SGprCjFMUlRudGJaQVpuZXppdk1rL0tw
            VkZTUHBmditEaWgyeU9FQVZ4Y2xwZUkKLS0tIFBFMDdZTzNkR2Vlc21GMjIvaU9l
            QjJSYkdjcjB1b1NpQmx1NitnWjNRSGMKaJ/w9l9WcFrSOz9pkHRzh7jJQmwQZDmc
            A/dGljXsmc6BZ2ZCb9Fg0QJZkbnYLosIfkkVu2Hg8maHxTOfpu4NzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12lxqhul385qtempx02gj7emy4cep7mesyqlgzjsv4w5xpl5n692s65v4ys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T08:17:00Z"
    mac: ENC[AES256_GCM,data:MLDmggbEYfgJuhxttObg3MxUctUZ0dLpFGFlOSrLtAqxFI5/aczFlG7BF/kign3eL18bXMfTfm+UuIzaZav1ZrNOyS78CmP/U+987mt2LQhM8AoRTao4guM1k7xgUTZltLcWH9aGQBKKQVLfJ7YdIPMJO+b8ow7G/lTXRaAzXrg=,iv:S7cv7xqOWo1oxLhllO4VZkBwQXJmuNIG+yZVwk3u6q0=,tag:WCyF5EewOA86KgHMTSttFQ==,type:str]
    version: 3.13.1
