apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-browser-auth
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-api
  oidc:
    provider:
      issuer: https://auth.mam.jku.internal
    clientID: jam-web
    clientSecret:
      name: envoy-oidc-client
    redirectURL: https://api.mam.jku.internal/oauth2/callback
