# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-masterkey
    namespace: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:G66kcDslU5OkYTy8tP9lwCT28rsh9YN4ffvlzw37KCk=,iv:T8A+1Ev0FblADc965OmlPcZ9Q6U1Jw/jlt3vZ4o4nXk=,tag:W1EpwXqEyzx07Etyfb1j8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRU9xWWpXcmszZk9ocCtv
            Mm94OG1Tdko2OGZMOTdmNUxSM3NiUEE2aXpnCkd0L0xwaDZOVkdaT1RpUiszRmlD
            WTYxTE9Zd2w0c1NnWGViZ3Q0bTJSMjAKLS0tIGN6UDMyQVBSRnh6UnBKRGRNUDFS
            RlF0SHBoU3JhdjdJNENVY29JRmpuY1kKYdpMFGOMPq1iIL+58SEqjDiEf8wCYoER
            8YBlaRK7QXcVDrqPBp34p5eignyHtRxfDANkVaN/lR79psqIv7qg3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12lxqhul385qtempx02gj7emy4cep7mesyqlgzjsv4w5xpl5n692s65v4ys
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T10:31:33Z"
    mac: ENC[AES256_GCM,data:ADMp46ZEQ0PtLhEw1Us7FjT2folNCanFf+m9+WbQin+DlWZPN+uQYPOq/IEJ8YWWgk/9iIcwL6+LbFE/0tXjDvT5yEqoa0foISnL4sdvwE7JfsNI3Hqx5BHbjfW1PQit0Sx3ONQq3C7WRfsrbBApcvO9KHkVzK0wTyAZIVkH+g4=,iv:iFYhc6PSTZDA40Djyh2IBfvF6DO9rlfpNGePAZyX4TY=,tag:R04zDwoTsLBJnJ5CXJwrSQ==,type:str]
    version: 3.13.1
