apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: zitadel-auth-issuer
  namespace: kube-system
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: zitadel-auth-issuer
  validation:
    hostname: auth.mam.jku.internal
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: jam-local-root-ca-bundle
