apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hubble-ui-oidc
  namespace: kube-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hubble-ui
  oidc:
    provider:
      issuer: https://auth.mam.jku.internal
      backendRefs:
        - name: public-api-internal
          namespace: envoy-gateway-system
          port: 443
    clientID: hubble-ui
    clientSecret:
      name: hubble-ui-oidc-client
    redirectURL: https://hubble.mam.jku.internal/oauth2/callback
