apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-class.yaml
  - public-gateway.yaml
  - public-gateway-internal-service.yaml
  - auth-issuer-backend-tls-policy.yaml
  - operator-ui-reference-grants.yaml
